stages:
  - deploy

include:
  - project: 'rickselby-linode-setup/gitlab-ci-templates'
    file: '/deploy-template.yml'

variables:
  COMPOSE_FILE_PATH: docker-compose.yml

deploy:
  extends: .docker-template
  stage: deploy
  script:
    - eval $COMPOSE_COMMAND pull
    - eval $COMPOSE_COMMAND build --pull
    - eval $COMPOSE_COMMAND up -d --remove-orphans
  only:
    - master
