version: '2.4'

services:
  app:
    container_name: the-versions-app
    build: wordpress
    restart: always
    volumes:
      - site:/var/www/html

  web:
    container_name: the-versions-web
    build: nginx
    restart: always
    depends_on:
      - app
    environment:
      VIRTUAL_HOST: www.the-versions.co.uk
      LETSENCRYPT_HOST: www.the-versions.co.uk
      LETSENCRYPT_EMAIL:
    volumes:
      - site:/var/www/html

  redirect:
    container_name: the-versions-redirect
    image: morbz/docker-web-redirect
    restart: always
    environment:
      VIRTUAL_HOST: the-versions.co.uk
      LETSENCRYPT_HOST: the-versions.co.uk
      LETSENCRYPT_EMAIL:
      REDIRECT_TARGET: www.the-versions.co.uk

volumes:
  site:

networks:
  default:
    name: the-versions
