version: '2.4'

services:
  app:
    container_name: the-versions-app
    image: wordpress:5.1-php7.3-fpm-alpine
    restart: always
    depends_on:
      - db
    volumes:
      - site:/var/www/html

  web:
    container_name: the-versions-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - app
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - site:/var/www/html

  db:
    container_name: the-versions-db
    image: mysql:5
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: 'the-versions'
      MYSQL_USER: 'the-versions'
      MYSQL_PASSWORD: 'localpassword'
    volumes:
      - db:/var/lib/mysql

  redirect:
    image: morbz/docker-web-redirect
    restart: always
    environment:
      VIRTUAL_HOST: ${REDIRECT_VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${REDIRECT_VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      REDIRECT_TARGET: ${VIRTUAL_HOST}

volumes:
  db:
  site:

networks:
  default:
    external:
      name: the-versions
